wingzy/backflip

public/stylesheets/base.css
views/home/home.hbs
views/partials/menu.hbs

Anchor and delete button (fix)

---

locales/en-UK.json
public/stylesheets/premium_features.css
views/partials/premium_features.hbs

Ce sont des features fictives pour l'instant, mais permettent de montrer l'évolution possible des features premium !

adding new 'futures' features

---

views/profile.hbs

fixing edit button

---

app.js

Revert "Redirect to frontflip onboard"

---

app.js

Revert "Revert "Redirect to frontflip onboard""

---

app.js

Revert Redirect to frontflip onboard

---

api/user/api_user.js
models/user.js
views/onboard/welcome.hbs

- Fix : post request to frontflip => now get request
- Fix : api route to welcome user => a function wasn't valid
- Fix : do not fetch salt & hashedPassword from mongodb User object

Fix some bugs

---

api/record/api_record.js
models/record.js

To test : merge organisation record to "all" record

Implements MERGE records API

---

.forestadmin-schema.json
api/record/api_record.js
helpers/googleUser_helper.js
models/record.js
models/user.js

Use GoogleUser object to populate user records

---

.forestadmin-schema.json
api/email/api_email.js
locales/en-UK.json
locales/fr.json
models/user.js
views/emails/unsubscribe.hbs
views/hbs.js

Unsubscribe API & layout

---

models/agenda_scheduler.js

Do not send email to unsub users
Batch : add slack logs

Batch reactive users : do not send email to unsubscribed users

---

api/api.js
api/statistics/api_search.js

Search logs API

---

helpers/url_helper.js
public/stylesheets/footer.css
public/stylesheets/home/styles_askdemo.css
views/hbs.js
views/home/home.hbs
views/partials/footer.hbs

Update homepage footer

---

api/user/api_user.js
helpers/client_auth_helper.js
helpers/invitationCode_helper.js
locales/fr.json
models/agenda_scheduler.js
models/email/email_user.js

- Auth backflip client
- Send invitation CTA after 3 days
- Fetch invitation code

Send invitation CTA after 3 days

---

api/user/api_user.js
helpers/googleUser_helper.js
helpers/invitationCode_helper.js
helpers/linkedinUser_helper.js
models/email/email_user.js

Auth API refacto : Remake api calls

---

api/email/api_email.js
api/user/api_user.js
helpers/client_auth_helper.js
helpers/email_helper.js
helpers/invitationCode_helper.js
locales/en-UK.json
models/email/email_user.js

Il me reste à modifier quelques mails plus les traductions:
mails mis à jour :
-welcome
-confirmation invitation
-invitation accepté

New email template with footer

---

api/record/api_record.js
locales/en-UK.json
models/record.js

**READY**
- Sync api route: return records created & records updated

Rebuild - api bulk record

---

api/authorization/organisation.authorization.js
controllers/organisation.controller.js
controllers/record.controller.js
models/record.js

Organisation authorization: update method to find org id
record: return property "hashtags" of hashtags of the record
organisation: populate featuredWingsFamily

Update API: record, organisation & organisation authorization

---

api/routes/record.api.js
controllers/record.controller.js

- User should owns the record OR be an admin in the organisation
- Superadmin can delete all

Record API : Add DELETE route

---

controllers/email.controller.js
helpers/email_helper.js

- From Name : sender name
- From Email : question@wingzy.com

Update help request email

---

controllers/email.controller.js
helpers/connectionLog_helper.js
locales/en-UK.json
locales/fr.json
models/agenda_scheduler.js

**READY**
UPDATE "backflip" client with scope: connectionLog

Update reactivate email

---

controllers/user.controller.js

API : get User : me : populate orgsAndRecords

---

api/routes/record.api.js
api/routes/recordActions.api.js
controllers/record.controller.js
helpers/clap_helper.js

API : record : merge

---

api/routes/user.api.js
controllers/user.controller.js

Api users : get all users in organisation

---

api/api.js
api/authorization/access.authorization.js
api/passport/strategy.js
api/routes/agenda.api.js
controllers/agenda.controller.js
controllers/email.controller.js
controllers/record.controller.js
controllers/user.controller.js
helpers/email_helper.js
locales/en-UK.json
models/agenda_scheduler.js
models/auth/tokenModels.js

READY
NEED NEW client : backflip-auth + ENV VAR (backflip-auth)

New onboard emails workflow

---

api/routes/recordActions.api.js
controllers/record.controller.js
models/record.js

Update algoliaSync method
+ add Google Sheet column

Record: "auto add to child selection" property

---

controllers/user.controller.js
models/record.js

Default : record.welcomed = false
When user is welcomed to an organisation, the record linked is updated to : record.welcomed = true

Allow record control depends on welcomed status

---

api/api.js
api/authorization/access.authorization.js
api/routes/email.api.js
api/routes/skillsProposition.api.js
controllers/email.controller.js
controllers/skillsProposition.controller.js
controllers/statistic.controller.js
helpers/email_helper.js
locales/en-UK.json
models/skillsProposition.js

Skills Proposition
- Model
- API : GET ONE / POST / PUT (status)
- Controller : GET ONE / CREATE ONE / UPDATE ONE (status)
- Access control
- Email : Propose skills
- Email : Proposition accepted

Implements skills proposition

---

models/organisation.js

`features: {
claps: Boolean,
askForHelp: Boolean,
proposeWings: Boolean,
canInvite: Boolean,
map: Boolean
}`

Organisation : add features control field

---

api/authorization/access.authorization.js
controllers/record.controller.js
controllers/user.controller.js
models/user.js

user.orgsAndRecords.secondaryRecords = array of records
API : record : get populated : is used to create the first record : primary record  = user.orgsAndRecords.record
API : record : post : is used to create a new record which will be added to user secondary records.

User can have secondary records in an organisation
